
import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="text-center mt-12 py-4 border-t border-slate-800">
      <p className="text-sm text-slate-500">
        ATHP Visualization Interface | Generated by a world-class senior frontend React engineer.
      </p>
    </footer>
  );
};

export default Footer;
